name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Dependecies
        run: |
          npm ci

      - name: Build
        run: npm run build

      - name: Save version
        id: version
        run: echo ::set-output name=tag::$(echo $(node -p -e "require('./package.json').version"))

      - name: Increase version
        run: npm version patch

      # - name: Push new version
      #   run: git push

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker image
        # run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/cd-ci-react:${{steps.version.outputs.tag}}
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/cd-ci-react:latest

      - name: Push to Docker Hub
        # run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/cd-ci-react:${{steps.version.outputs.tag}}
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/cd-ci-react:latest

      # - name: Call Portainer Webhook to Update Service
      #   id: callportainerwebhook
      #   if: steps.build.outcome == 'success'
      #   continue-on-error: true
      #   run: |

      #     CODE=`curl --write-out '%{http_code}' \
      #         --silent \
      #         --output /dev/null \
      #         --request POST \
      #         --url 'http://localhost:9000/api/webhooks/08aa3890-8cbf-4e4a-8aad-dd50a9b05bc3'`

      #     if [ $CODE != "204" ]
      #     then
      #         echo $CODE
      #         echo "FAILURE"
      #         exit 1
      #     else
      #         echo $CODE
      #         echo "SUCCESS"
      #         exit 0
      #     fi
